package model

const (
	// LowerABC – ...
	LowerABC = "abcdefghijklmnopqrstuvwxyz"
	// UpperABC – ...
	UpperABC = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	// SpecSymbols – ...
	SpecSymbols = "!@#$%^&*()-_=+[]{}|;:'\",.<>?/`~"
	// Digits – ...
	Digits = "0123456789"
	// All – ...
	All = LowerABC + UpperABC + SpecSymbols + Digits
)
